## 1. Basic Data Structures
Demonstrating sets, lists, tuples, and dictionaries in Python.

In [1]:
my_set = {1, 2.0, False}  # False is equivalent to 0, so only unique values remain
print("Set:", my_set)

Set: {False, 1, 2.0}


In [3]:
my_list = [1, 2, 3, 'AI', True]
print("List:", my_list)

List: [1, 2, 3, 'AI', True]


In [5]:
my_tuple = (1, 'Python', 3.14)
print("Tuple:", my_tuple)

Tuple: (1, 'Python', 3.14)


In [7]:
my_dict = {'name': 'Aizaz', 'course': 'AI', 'semester': 4}
print("Dictionary:", my_dict)

Dictionary: {'name': 'Aizaz', 'course': 'AI', 'semester': 4}


## 2. Student Information Dictionary
Using nested dictionaries to store detailed info.

In [10]:
student = {
    "name": "Aizaz Kiramat",
    "roll_number": "23MDTLE321",
    "department": "Telecommunication Engineering",
    "semester": 4,
    "university": "UET Mardan",
    "email": "aizazkiramat@gmail.com",
    "phone": "03198593852",
    "address": {
        "street": "City College Chowk",
        "city": "Mardan",
        "district": "Mardan",
        "province": "Khyber Pakhtunkhwa",
        "country": "Pakistan"
    }
}
print("Province:", student['address']['province'])

Province: Khyber Pakhtunkhwa


## 3. Conditional Statements and Loops
Using `if`, `for`, and `while`.

In [12]:
x = 10
if x > 0:
    print("Positive number")
elif x == 0:
    print("Zero")
else:
    print("Negative number")

Positive number


In [14]:
for i in range(5):
    print("Loop iteration:", i)

Loop iteration: 0
Loop iteration: 1
Loop iteration: 2
Loop iteration: 3
Loop iteration: 4


In [16]:
i = 0
while i < 3:
    print("While loop:", i)
    i += 1

While loop: 0
While loop: 1
While loop: 2


## 4. Functions
Creating reusable blocks of code.

In [32]:
def function1(): # no arguments
    print("welcome to function1")

In [34]:
function1()

welcome to function1


In [36]:
# two types of function parameterized and non parameterized
def add(a,b):
    print("a+b=",a+b)

In [38]:
add(10,20)

a+b= 30


In [40]:
    add(b=2,a=3)

a+b= 5


## 5. Error Handling
Handling potential runtime errors using `try` and `except`.

In [24]:
try:
    num = int(input("Enter a number: "))
    print("You entered:", num)
except ValueError:
    print("That's not a valid number!")

Enter a number:  a


That's not a valid number!


## 6. Practice Problem
Check if a number is even or odd.

In [26]:
def check_even_odd(num):
    if num % 2 == 0:
        print("Even")
    else:
        print("Odd")

check_even_odd(7)

Odd


## 7. Extras
Just experimenting with sets.

In [28]:
print(set([1, 2, 2, 3, 1]))

{1, 2, 3}


In [42]:
#Use of numpy Library

In [44]:
import numpy as np

In [46]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
arr=np.array([1,2,3]) # one dimentional Array
print(arr)

[1 2 3]


In [50]:
arr.ndim

1

In [52]:
twodim_array=np.array([[1,2,3],[4,5,6],[7,8,9]]) # Two dimentional Array
print(twodim_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
twodim_array.ndim

2

In [56]:
# Now use of numpy library is start from here 

In [58]:
Array_of_Zeros=np.zeros((2,3)) #Type of array where all the elements are Zero
print(Array_of_Zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [60]:
Array_of_ones=np.ones((2,3)) # Type of Array whre all the elements are one's
print(Array_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [62]:
Array_of_full=np.full((2,2),5)  # Type of Array where all the elements are set to 5
print(Array_of_full)

[[5 5]
 [5 5]]


In [64]:
Array_of_Identity=np.eye(3)  # Identity Array
print(Array_of_Identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
array = np.arange(0, 10, 2) #Sequence Array
print(array)

[0 2 4 6 8]


In [72]:
rand_ints = np.random.randint(0, 10, size=(3, 3)) #Random Array
print("Random Integers:\n", rand_ints)

Random Integers:
 [[5 3 9]
 [4 9 7]
 [7 5 0]]
